# -*- mode: ruby -*-
# vi: set ft=ruby :

ipadress = "192.168.56.11"

Vagrant.configure("2") do |config|
  config.vm.box = "oki2a24/centos-7-x86_64"
  config.vm.network "private_network", ip: ipadress
  config.vm.synced_folder "synced_folder/ec-cube/", "/var/www/ec-cube",
    create: true, mount_options: ['dmode=777', 'fmode=766']
  config.vm.provision "shell", path: "../scripts/cen-7-init.sh"
  config.vm.provision "shell", path: "../scripts/cen-7-httpd.sh"
  config.vm.provision "shell", path: "../scripts/cen-7-php5.4.sh"
  config.vm.provision "shell", path: "../scripts/cen-7-phpmyadmin.sh"
  config.vm.provision "shell", path: "../scripts/cen-7-mariadb5.5.sh"
  config.vm.provision "shell", path: "../scripts/cen-7-ec-cube-3-mariadb.sh"  
end
