# -*- mode: ruby -*-
# vi: set ft=ruby :

ipadress = "192.168.56.11"

Vagrant.configure(2) do |config|
  config.vm.box = "oki2a24/centos-6-x86_64"
  config.vm.network "private_network", ip: ipadress
  config.vm.provision "shell", path: "../scripts/cen-6-init.sh"
  config.vm.provision "shell", path: "../scripts/cen-6-httpd.sh"
  config.vm.provision "shell", path: "../scripts/cen-6-php5.3.sh"
  config.vm.provision "shell", path: "../scripts/cen-6-mysql5.1.sh"
  config.vm.provision "shell", path: "../scripts/cen-6-phpmyadmin.sh"
end
