# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "oki2a24/centos-7-x86_64"
  config.vm.provision "shell", path: "../scripts/cen-7-upgrade-vagrant-box.sh"
end
